### ISSUE TITLE
error AC1000: Unknown build error: Picked up JAVAOPTIONS: -Djava.net.preferIPv4Stack=true

### ISSUE THREAD

**Issue by baruchl** [tunnelvisionlabs/antlr4cs#103]
Hello,
I'm trying to use the ANTLR 4.3 nuget package in VS2013, and when compiling I get the following compilation error:
error AC1000: Unknown build error: Picked up JAVAOPTIONS: -Djava.net.preferIPv4Stack=true

looking into my environment varaibles, I do have a JAVAOPTIONS varaible with the value 
-Djava.net.preferIPv4Stack=true

When double clicking the error, it take me to the Antlr4ClassGenerationTask  in the Antlr.Targets  file.

I don't know if this is the desired behavior, but none of the classes from the Obj\Debug folder are recognized in the development environment.

Any help appreciated.

Thanks,
Busi

**Comment by sharwell** [comment]
The AC1000 message is being reported as an error because the code that calls out to Java during the build doesn't recognize the line "Picked up _JAVA_OPTIONS" line which it's printing. The only way with the current release to suppress that message is to undefine the _JAVA_OPTIONS environment variable, but I'll look into improving the handling of this for the next release.

The classes in the intermediate output folder (obj\Debug) are being ignored by the IDE because you have ReSharper installed. ReSharper replaces Visual Studio's built-in IntelliSense functionality with proprietary behavior that [does not work with ANTLR](https://youtrack.jetbrains.com/issue/RSRP-265402).

**Comment by baruchl** [comment]
Hi,
Thanks Sam. Just to close this issue - there is no connection between the compilation error described above and the behavior of the classes generated in Obj\Debug.

So, to solve the Obj\Debug, I simply added those files to my solution using "Add as Link".
I'm still getting the compilation error "error AC1000: Unknown build error: Picked up JAVAOPTIONS: -Djava.net.preferIPv4Stack=true", but it doesn't prevent me from running the solution.

Thanks a lot for the quick help.
Busi

**Comment by lextm** [comment]
Reproduced in https://travis-ci.org/lextm/restructuredtext-antlr/builds/323655907
```
/home/travis/.nuget/packages/antlr4.codegenerator/4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m [/home/travis/build/lextm/restructuredtext-antlr/ReStructuredText/ReStructuredText.csproj]
```
Luckily it does not fail the build, so can be safely ignored.
