### ISSUE TITLE
Missing net35 full assembly

### ISSUE THREAD

**Issue by ViceIce** [tunnelvisionlabs/antlr4cs#107]
At [4.5.0-alpha002](https://www.nuget.org/packages/Antlr4.Runtime/4.5.0-alpha002) the net35 folder is missing and our build scripts require it. Is it possible to add it to the package?

**Comment by sharwell** [comment]
The .NET 3.5 assembly didn't change. It was just in a folder with the wrong name, and that caused NuGet to think that a certain group of users could not use this package. You'll need to potentially update your build script in a few ways (NuGet handles these automatically in most cases, but it sounds like you have custom scripts in addition to what NuGet provides):

1. The name of the assembly changed from Antlr4.Runtime.net35.dll to just Antlr4.Runtime.dll (and the same for all the other supported runtimes).
2. The .NET 3.5 assembly is in a **net35-client** folder instead of just **net35**.
3. The .NET 4.0 assembly is in a **net40-client** folder instead of just **net40**.

**Comment by ViceIce** [comment]
We are building our project for net35 and net45. To build we replace the ´net45´ part of the hintpath with an msbuild variable (powershell script after nuget update-package). There we have no knowledge that we have to use the net35-client folder.

**Comment by sharwell** [comment]
@ViceIce Is your project open source by any chance? This is a very interesting problem to me and I want to help find a great long-term solution.

**Comment by sharwell** [comment]
@ViceIce You should have received an invitation to join an **antlr4cs** chat room on gitter. I've been very happy with that service; since you are clearly an active contributor to the project I'd love to discuss some of your concerns there and see if we can address them in an upcoming release.

**Comment by ViceIce** [comment]
Found a new workaround to use net35-client assemblies, so this is no longer needed.

**Comment by sharwell** [comment]
Happy to hear you were able to update your build configuration to handle the new directory structure. :+1: 

Tagged as **invalid** so people don't think the .NET 3.5 support was removed from the release. :smile:

**Comment by ViceIce** [comment]
Yes, we use the new workaround we [discussed](https://gitter.im/tunnelvisionlabs/antlr4cs?at=55671c2abeed96397ea72504) ealier.

Taggging as invalid is fine. :+1:
