### ISSUE TITLE
"New Item"s not visible when creating Portable Class Libraries in VS2013

### ISSUE THREAD

**Issue by sebandraos** [tunnelvisionlabs/antlr4cs#114]
Hi Sam,
When attempting to add a new item in a PCL solution I'm not being presented the same new item list (with ANTLR Grammars etc.). I have the ANTLR extension, ANTLR4.Runtime and ANTLR4 from NuGet. This seems like an odd behaviour because I do get the full list when creating another type of solution e.g. a Console Application.
Thanks in advance for any suggestions,
Seb

**Comment by sharwell** [comment]
@sebandraos This functionality (grammar templates) is actually part of the ANTLR extension for Visual Studio, which is part of a different repository:

https://github.com/tunnelvisionlabs/LangSvcV2

It definitely sounds like a bug due to an oversight in the templates. I recommend posting this issue on the other repository and we can take it from there. :+1:

**Comment by sebandraos** [comment]
Thanks for the heads up. I have now opened a new issue over there (https://github.com/tunnelvisionlabs/LangSvcV2/issues/61)
