### ISSUE TITLE
Make ANTLR 4.5.3 accessible from NuGet

### ISSUE THREAD

**Issue by joce** [tunnelvisionlabs/antlr4cs#137]
I see that ANTLR 4.5.3 runtime is accessible from the website (http://www.antlr.org/download.html), however, the latest version that is available from NuGet is 4.5.0-alpha003. Updating the version available from NuGet to the latest version would be much appreciated.

**Comment by sparticus1701** [comment]
I would also like to see this; I have been working with 4.5.0-alpha003 and don't want to backport, but I also have deadlines coming up!

**Comment by sharwell** [comment]
:memo: Keep in mind that the ANTLR 4 runtime distributed through NuGet is actually a highly-optimized C# runtime which is different from the version distributed through the link above. The two are not API compatible. The NuGet package includes an embedded copy of the ANTLR code generator in order to provide these unique features.

**Comment by sparticus1701** [comment]
Thanks for the clarification.  I am still wondering when the 4.5.0 builds will get out of alpha, as we've been building a NuGet package involving it and it won't allow the release version to include the prerelease package.

We're using .NET 4.6.1 and VS2015, and I don't know how the 4.3 package would work in those.

**Comment by KvanTTT** [comment]
Why this runtime is not merged with main ANTLR repo?

**Comment by sharwell** [comment]
@KvanTTT The main ANTLR Tool isn't able to generate the code used by this optimized runtime because it's missing some of the necessary static analysis features. In theory the code generation templates could have been modified in such a way that users not needing these features could use the main ANTLR Tool to generate C# code, but the C# target now distributed with the main ANTLR Tool was derived from my work here and rendered fully incompatible at an API level without consulting me or asking if a better option existed (i.e. one runtime library could have been used for both users of the main Tool and users of the optimized Tool, but that is now impossible).

**Comment by sharwell** [comment]
I'm currently working on updating the Java release of the optimized runtime, from which this C# build is developed. Once it is up-to-date with the 4.5.3 release, I can update the C# build to match.

**Comment by sharwell** [comment]
:memo: I just published 4.5.3-rc1 to NuGet. See [Antlr4.Runtime](https://www.nuget.org/packages/Antlr4.Runtime/4.5.3-rc1) and [Antlr4](https://www.nuget.org/packages/Antlr4/4.5.3-rc1).

**Comment by joce** [comment]
Thanks a bunch, Sam! :-) Much appreciated.
Also, not to push my luck, but do you have any plans to bring the ANTLR Language Support extension to VS 2015?

**Comment by sharwell** [comment]
@joce Visual Studio 2015 had bugs in RTM and Update 1 (at least) which resulted in problems updating support fro the extension. See tunnelvisionlabs/LangSvcV2#63.

**Comment by KvanTTT** [comment]
@joce, [Antlr4Code](https://visualstudiogallery.msdn.microsoft.com/836c87a4-b182-4899-b014-ae40f4e32b4b) is pretty good VS 2015 extension for grammars development.

**Comment by joce** [comment]
@sharwell Ho. :-(

**Comment by joce** [comment]
@KvanTTT I tried it and it's kinda okay, but the fact that you can't really change many of the font and colors settings makes it a no go for me.

**Comment by sharwell** [comment]
@KvanTTT @joce I just uploaded a new release of the [ANTLR Language Support](https://visualstudiogallery.msdn.microsoft.com/25b991db-befd-441b-b23b-bb5f8d07ee9f) extension which should work in Visual Studio 2015.

**Comment by joce** [comment]
This is amazing! Thank you so much!

**Comment by kahgeh** [comment]
Quick question - will 4.5.x be released as a stable build anytime soon.  I have restrictions over the use of a non-stable build.

**Comment by sharwell** [comment]
@kahgeh I should be able to. Have you had the chance to try out the RC build?

**Comment by kahgeh** [comment]
Yes, I have and it works like a charm for the work I am doing.

**Comment by clembou** [comment]
Hi @sharwell, we are using the latest Antlr4 package too as a nuget dependency in some of our projects and have come across the same issue as @kahgeh: basically nuget is complaining about the Antlr package being a pre-release and will not let us issue a stable release of for our own packages that depend on it. So far the latest RC has been working well for us, it would be awesome if you could publish a stable version so that we can get rid of that issue. 

We consider rolling back to the latest stable package, but it is version 4.3.0 from July 2014 so is a bit old and lacks features we need.

**Comment by sharwell** [comment]
@clembou I'll try to get it published today.

**Comment by clembou** [comment]
Awesome! Thanks a lot @sharwell !

**Comment by kahgeh** [comment]
Thanks for releasing it  @sharwell

**Comment by polysg** [comment]
Many thanks @sharwell; really appreciate the prompt response!
