### ISSUE TITLE
How to change ouput path of generated files?

### ISSUE THREAD

**Issue by gpetrou** [tunnelvisionlabs/antlr4cs#160]
Is it possible to only change the output path of the generated files?

**Comment by sharwell** [comment]
The output is placed in the intermediate build directory. You can change the output path of generated files by setting the `BaseIntermediateOutputPath` property in your project file. Is there something more specific you were looking for?

**Comment by daniel-smith** [comment]
The output is actually in `IntermediateOutputPath` rather than `BaseIntermediateOutputPath`, meaning that the generated files also go under the `Configuration` folder (e.g. debug or release). This makes it difficult to manage in automated build environments. Also, changing `BaseIntermediateOutputPath` or `IntermediateOutputPath` impacts the entire project including non-related files, which may not be desirable. Why not provide a configurable property for this?

**Comment by sharwell** [comment]
@daniel-smith You are correct that the intermediate directory contains all of the intermediate output, and not just the generated files.

> This makes it difficult to manage in automated build environments.

Can you provide more information and/or examples about this? I may already have examples available for how to address your scenario(s).

> Why not provide a configurable property for this?

There are a few reasons why this is not currently configurable. This location has the following advantages which makes it ideal for generated code output (and not just from this tool):

1. It's generally excluded from source control, so building the project doesn't result in files getting added to source control or reported as changed, and no additional steps are required to exclude the files.
2. It makes it easy to seamlessly integrate with both the Build and Clean commands, ensuring that the build output is always accurate with respect to the grammar files in the project.

**Comment by daniel-smith** [comment]
@sharwell - thanks for your quick response. Re my comment about difficulty in automated build environments, I'm just referring to the fact that if we are building in release rather than debug, we need to accommodate for the fact the the generated files will live in a different folder. E.g. I need to link to files that live in obj/debug while I'm developing, but when I'm building a release package those files live in obj/release. Happy to hear if you have some neat solutions around this.

**Comment by daniel-smith** [comment]
Just an update, I've actually taken the advice here - https://github.com/antlr/antlr4/tree/master/runtime/CSharp - which suggests that we can directly use the latest antlr4 tool to gen C# bindings. I've been able to successfully add this to my build without too much effort, and can specify any output directory for the generated files.

**Comment by sharwell** [comment]
> E.g. I need to link to files that live in obj/debug while I'm developing, but when I'm building a release package those files live in obj/release

The files are automatically added to the build. There is no need to link them yourself.

> Just an update, I've actually taken the advice here 

Keep in mind that I don't work on that port at all. You'll lose the [features and performance](https://github.com/tunnelvisionlabs/antlr4/blob/master/doc/optimized-fork.md) gained by the original C# runtime I maintain, and you'll also no longer be covered by the much stronger breaking changes policy covering by releases (the standard release breaks users at each minor version, where mine has maintained compatibility at least since 4.2).

**Comment by daniel-smith** [comment]
> The correct files are automatically added to the build. There is no need to link them yourself.
Just wondering what you mean by this. I had to manually link the generated files from the obj/debug directory. Seems like I'm missing something.

**Comment by sharwell** [comment]
@daniel-smith Linking is not required. They will be part of the compiled build output whether or not you add those links.

**Comment by daniel-smith** [comment]
So it does indeed. Very nice.
