### ISSUE TITLE
 Antlr4 doesn't support .NetCoreApp 

### ISSUE THREAD

**Issue by makhan7** [tunnelvisionlabs/antlr4cs#167]
Does Antlr4 support .NetCoreApp yet? as I am having several issues such  try to generate *g4 (which basically have lexer and parser classes but no help).
I have read almost all the articles on github regarding Antlr4/.NetCore but so far no help.

We are going to rewrite our app because of Antrl4 doesn't support .Net Core and we are bringing up full .net Framework. Are we going in the right direction? I tried everything but our .NetCore dependent solution doesn't seems to work with Antrl4.

java.exe : error(31):  ANTLR cannot generate CSharp_v4_5 code as of version 4.5.3At line:1 char:1
+ java -jar antlr-4.5.3-complete.jar *.g4 -o Generated -Dlanguage=CSharp_v4_5 -pac ...

http://stackoverflow.com/questions/41112478/antlr4-runtime-4-5-3-does-not-support-framework-netcoreapp-version-v1-0

**Comment by sharwell** [comment]
The first release of ANTLR 4 which should support .NET Standard is [4.5.4-beta001](https://www.nuget.org/packages/Antlr4/4.5.4-beta001). If you want to generate code on the command line, you will need to use the Jar files located in the [Antlr4.CodeGenerator](https://www.nuget.org/packages/Antlr4.CodeGenerator/4.5.4-beta001) package from NuGet. However, the goal (and only truly intended scenario) is to install the NuGet package and allow it to automatically generate code from your grammars when the project is built.

**Comment by makhan7** [comment]
thank you for your reply Sam, My scenario is I have two separate projects. created to test ANTLR4 before using ANTLR4 directly with the main .NetCore solution.
Project 1 (Standard .Net Framework) ----everything works with ANTLR
Project 2 (.Net Core App) ------ not working even use Antlr.CodeGen
do you have a working copy ANTLR with dotnet Core app or steps to generate g4 file?

I tried to generate code using package manager console here is my command
java -jar antlr-4.5.3-complete,jar *.g4 -o Generated -Dlanguage=CSharp_v4_5 -package
and getting unable java.exe : Error: Unable to access jarfile antlr-4.5.3-completeAt line:1 char:1

or when solution build I see
Error	NU1002	The dependency Antlr4.Runtime.Standard 4.6.0 does not support framework .NETCoreApp,Version=v1.0.	CalculatorCore	C:\Users\makhan8\Downloads\Calculator\CalculatorCore\project.json	10

**Comment by sharwell** [comment]
@makhan7 I'll have to take a closer look and build some examples to make sure everything is working fine. That said, I can see that you're using the wrong dependency. The NuGet package for the C# target runtime library is [Antlr4.Runtime](https://www.nuget.org/packages/Antlr4.Runtime/4.5.4-beta001).

**Comment by makhan7** [comment]
How can email or upload zip file with the source code here?  I have simple console apps one is dotnet core based another one is standard dotnet framework app.

**Comment by sharwell** [comment]
Thanks! It might be a few days before I get the chance but it's helpful to have a repo handy

**Comment by GeorgDangl** [comment]
[Here's also an example app](https://github.com/GeorgDangl/Dangl.Calculator) that's targetting NETStandard 1.3 with Antlr4.
Here's the build script I use on Windows machines:
``` batch
@echo off
SET JAVACOMMAND=java
where %JAVACOMMAND%
if %ERRORLEVEL% NEQ 0 (
	SET JAVACOMMAND=%UserProfile%/.nuget/packages/Antlr4.CodeGenerator/4.5.4-beta001/tools/ikvm.exe
)
%JAVACOMMAND% -jar %UserProfile%/.nuget/packages/Antlr4.CodeGenerator/4.5.4-beta001/tools/antlr4-csharp-4.5.4-SNAPSHOT-complete.jar Calculator.g4 -package Dangl.Calculator.Generated -o Generated -Dlanguage=CSharp_v4_5 -visitor -no-listener
```

**Comment by makhan7** [comment]
@GeorgDangl  your example includes NETStandard 1.3 with Antlr4. I am looking just .netcoreapp with antlr4

**Comment by sharwell** [comment]
@makhan7 netcoreapp1.0 supports netstandard1.5, which is in turn a superset of netstandard1.3. If @GeorgDangl's example runs under netstandard1.3 then it also runs under netcoreapp1.0 unless something is broken.

**Comment by GeorgDangl** [comment]
The [unit tests](https://github.com/GeorgDangl/Dangl.Calculator/blob/master/test/Dangl.Calculator.Tests/project.json#L19-L38) are running on netcoreapp1.0 and netcoreapp1.1 (as well as on the full .Net framework).
@makhan7, generally speaking, you can expect libraries to target `netstandard` platforms (which is basically just a definition of the API that is required for the library to work) and actual executables (like console applications or Asp.Net apps) to target an actual framework like `netcoreapp`.

**Comment by makhan7** [comment]
yes, everything is working now. I can successfully able to generate *g4 files. I am trying to upload a working copy

**Comment by lextm** [comment]
I think I don't think the above discussion provides the minimal developer experience. First, Microsoft brought back MSBuild support in .NET SDK preview 3 (now it is preview 4 and preview 5 is coming). Thus, project.json and xproj should be gone. Second, using a batch file to generate the parser/lexer is ugly.

I just tested with a preview 4 csproj project with dotnet build, and it failed with,
```
dotnet build SharpSnmpPro.Mib.NetStandard.csproj
Microsoft (R) Build Engine version 15.1.458.808
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\lextm\.nuget\packages\antlr4.codegenerator\4.5.4-beta001\build\Antlr4.CodeGenerator.targets(110,5): error MSB4062: The "Antlr4.Build.Tasks.Antlr4ClassGenerationTask" task could not be loaded from the assembly C:\Users\lextm\.nuget\packages\antlr4.codegenerator\4.5.4-beta001\build\.\Antlr4BuildTasks.net40.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\Users\lextm\Downloads\sharpmibsuite\SharpSnmpPro.Mib\SharpSnmpPro.Mib.NetStandard.csproj]
```
So there is still a gap to fill before ANTLR 4 fully works for .NET Core tooling.

**Comment by sharwell** [comment]
@lextm I believe I need to update the MSBuild integration so it references the .NET Standard version of MSBuild. Having the code generation automatically work on both Windows and other platforms will be *huge*. Right now I'm working on porting the code generation tool from Java to C# to fully eliminate the Java dependency. It's a .NET Standard console app, so it will work with the new MSBuild integration seamlessly.

**Comment by sharwell** [comment]
@lextm Between the C# port of the tool itself (#175) and a new MSBuild integration targeting .NET Standard (#179), it should be possible to incorporate ANTLR 4 into the .NET Core tooling. I just have a few things that I haven't quite figured out yet:

1. We only want to use the new build tasks when building with Visual Studio 2015+ or with the new cross-platform releases of MSBuild for .NET Core. But we also don't want to lose support for Visual Studio 2010 through 2013, so that means including both build tasks assemblies in the NuGet package and finding a way to switch between them at runtime.
2. The new C# port of the code generator should probably be the preferred way to generate code, but it might not work with some older installations on Windows (in particular .NET 4.0 users that don't have 4.5+).
3. I'm not sure how this all works out with XBuild (#172), but I'm guessing the new code generator is much more likely to "just work" for those users.

**Comment by lextm** [comment]
@sharwell 

1. I think the scope should be set to Visual Studio 2017+ instead of 2015+, as .NET Core support in VS2015 is so fragile, and I am not sure if Microsoft later will fix it. It would be quite difficult if you want to also support VS2010-2013. Maybe a separate set of NuGet packages should be published.
2. I am not too much worried at .NET Framework 4.5+ requirement, as Microsoft officially stops supporting .NET Framework 4.0. Every developers should at least upgrade their own development machine to .NET Framework 4.5.
3. I suggest removing xbuild from supported list, if Mono ships MSBuild. It would be ideal to focus on MSBuild.

Just my 5 cents.

**Comment by sharwell** [comment]
@lextm

> I think the scope should be set to Visual Studio 2017+ instead of 2015+, as .NET Core support in VS2015 is so fragile ...

The limitation I was referring to is applied by MSBuild and NuGet support limitations. Microsoft released a stable API for MSBuild targeting .NET Standard with apparent support for MSBuild 14, which coincides with the version shipping with Visual Studio 2015 (or one of its updates). It's possible that it's not usable inside the IDE for .NET Core prior to Visual Studio 2017.

> I am not too much worried at .NET Framework 4.5+ requirement ...

The project provides builds supporting .NET 2.0+ being developed on machines running Visual Studio 2008 and newer. The .NET 3.5 Compact Framework support (the most challenging one in the current build) is actually provided at the request of a consumer. Due to NuGet limitations, there is manual work involved with using Visual Studio 2008. However, it's important that the work to support .NET Core not negatively impact users running Visual Studio 2010 with only .NET 4.0 installed.

These are the downsides of having such a widely used library with a code generation component during the build.

> I suggest removing xbuild from supported list ..

Currently the only truly supported build is MSBuild from Visual Studio 2010 or newer running on Windows. XBuild, all cross-platform systems, and Unity are items under consideration that I would like to support if possible but do not yet know how possible that is. Cross-platform MSBuild is the next priority though.

**Comment by lextm** [comment]
Just tested 4.6.1-beta001 in a netcoreapp1.1 console application and it seems to work.

**Comment by sebandraos** [comment]
The only issue I'm having is in testing a fresh .NETStandard library. Without using the ANTLR Language Support extension (in VS2017) I am unable to set the Build Action to Antlr4. I can, however force the change in the csproj and it works but the Build Action in the grammar file properties remains None. This is using the latest nuget package, 4.6.1-beta002. @sharwell Is this just a case of me jumping the .NETStandard gun?

**Comment by sharwell** [comment]
@sebandraos Can you file a new bug for that? I am able to reproduce it locally and want you to have the credit for finding it.

**Comment by sebandraos** [comment]
There we go, #193
