### ISSUE TITLE
Sync repository with antlr 4.6

### ISSUE THREAD

**Issue by KvanTTT** [tunnelvisionlabs/antlr4cs#168]

**Comment by sharwell** [comment]
@KvanTTT This is a complicated request that will be addressed a bit out of order. Since ANTLR 4.6 included massive changes to the unit test infrastructure that need to be modified to match the behavior differences in the optimized fork of ANTLR, I would allow up to 12 months for a complete sync to occur (based on how long it took the last time a major change like this took). I may end up discarding the changes to the test infrastructure during the merge, but I'm not sure about that yet.

In the meantime, all bug fixes which affect the optimized fork will be brought over into a 4.5.x patch release for the optimized fork.
