### ISSUE TITLE
4.6.1-beta001 issue with Antlr4.CodeGenerator.targets

### ISSUE THREAD

**Issue by ben-may** [tunnelvisionlabs/antlr4cs#188]
Upgrading from 4.5.0-alpha003 to 4.6.1-beta001

I see 
1>D:\packages\Antlr4.CodeGenerator\4.6.1-beta001\Antlr4.CodeGenerator.4.6.1-beta001\build\Antlr4.CodeGenerator.targets(110,5): error AC1000: Unknown build error: The system cannot find the file specified

Any idea what file it cannot find? Can I add any debugging flag to the Antlr4ClassGenerationTask to get more info?

**Comment by ben-may** [comment]
@sharwell Its just a standard .csproj, however, we wrap nuget packages in our own build system, which handles downloading them and placing them in our own packages folder.  So there is likely an issue with that, but its hard for me to figure that part out without knowing what file that target is looking for.

**Comment by sharwell** [comment]
:question: Do you have any files in your project with the build action set to **Antlr4Tokens**? I'm assuming not.

It's looking for the Java runtime. If you don't have one on the build system, it's looking for ikvm.exe which is included in the tools directory of the NuGet package.

**Comment by lextm** [comment]
I tested in both traditional .NET Framework class library and .NET Standard class library and could not reproduce this issue. There might be something special about this project @ben-may uses.

**Comment by ben-may** [comment]
ok thx guys, I bet it has something to do with our build system.  Will have to debug it later more.
I do have the ikvm.exe here:
D:\packages\Antlr4.CodeGenerator\4.6.1-beta001\Antlr4.CodeGenerator.4.6.1-beta001\tools\ikvm.exe
as well as the jar:
D:\packages\Antlr4.CodeGenerator\4.6.1-beta001\Antlr4.CodeGenerator.4.6.1-beta001\tools\antlr4-csharp-4.6.1-SNAPSHOT-complete.jar

The csproj contains these elements, it looks like its pointing to the base Antlr package instead of the CodeGenerator Package, that's likely my issue?

    <Antlr4JavaExecutable>D:\packages\Antlr4\4.6.1-beta001/Antlr4.4.6.1-beta001/tools/ikvm.exe</Antlr4JavaExecutable>
    <Antlr4JavaInstallation>D:\packages\Antlr4\4.6.1-beta001/Antlr4.4.6.1-beta001/tools/</Antlr4JavaInstallation>

**Comment by ben-may** [comment]
Yeah manually fixing those gets things working!
I'm guessing I just have the dependencies setup wrong or something in our build system.
I'll re-open if I find that its not my own issue :) 
Thanks for your time.

**Comment by sharwell** [comment]
@ben-may Yes those properties are not set as part of the standard installation so a problem there would be unique to your build system. Glad to hear it's working!

**Comment by igitur** [comment]
This error is caused by Antlr4 failing to find an appropriate version of Java. On a Windows machine, Antlr4 checks the registry first *before* it checks your environment variables to determine the suitable location of Java.

Shortly before I experienced the same problem, I had been consolidating the many instances of the Java Runtime Environment I had on my computer. I had *many* and I trimmed them down to only 1 instance of a 64b JRE and 32b JRE each. I removed the rest by just deleting their folders. Subsequently I checked that my user and system environment variables (specifically `JAVA_HOME`) still pointed to a valid Java directory. 

But I failed to realise that there are registry entries that have to be updated too. Possibly a reinstall of Java would fix the registry entries, but I reverted to just fixing them manually.

So the appropriate place in the Antlr4 code is at https://github.com/tunnelvisionlabs/antlr4cs/blob/master/runtime/CSharp/Antlr4BuildTasks/Antlr4ClassGenerationTaskInternal.cs#L144 .

```c#
       private string JavaHome
        {
            get
            {
#if !NETSTANDARD
                string javaHome;
                if (TryGetJavaHome(RegistryView.Default, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;

                if (TryGetJavaHome(RegistryView.Registry64, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;

                if (TryGetJavaHome(RegistryView.Registry32, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;
#endif

                if (Directory.Exists(Environment.GetEnvironmentVariable("JAVA_HOME")))
                    return Environment.GetEnvironmentVariable("JAVA_HOME");

                throw new NotSupportedException("Could not locate a Java installation.");
            }
        }

#if !NETSTANDARD
        private static bool TryGetJavaHome(RegistryView registryView, string vendor, string installation, out string javaHome)
        {
            javaHome = null;

            string javaKeyName = "SOFTWARE\\" + vendor + "\\" + installation;
            using (var baseKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, registryView))
            {
                using (RegistryKey javaKey = baseKey.OpenSubKey(javaKeyName))
                {
                    if (javaKey == null)
                        return false;

                    object currentVersion = javaKey.GetValue("CurrentVersion");
                    if (currentVersion == null)
                        return false;

                    using (var homeKey = javaKey.OpenSubKey(currentVersion.ToString()))
                    {
                        if (homeKey == null || homeKey.GetValue("JavaHome") == null)
                            return false;

                        javaHome = homeKey.GetValue("JavaHome").ToString();
                        return !string.IsNullOrEmpty(javaHome);
                    }
                }
            }
        }
#endif
```

Your `.\packages\Antlr4.CodeGenerator.4.6.3\build\Antlr4.CodeGenerator.targets` file (adjust for correct version number) has lines to set the `JavaVendor` and `JavaInstallation` variables:

```xml
    <Antlr4JavaVendor Condition="'$(Antlr4JavaVendor)'==''">JavaSoft</Antlr4JavaVendor>
    <Antlr4JavaInstallation Condition="'$(Antlr4JavaInstallation)'==''">Java Runtime Environment</Antlr4JavaInstallation>
```

So, in my case at least, the appropriate registry settings were located in `HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment`

To fix the incorrect registry:

- Ensure that `CurrentVersion`'s value (in my case `1.8.0_91`) has a corresponding key 
- Ensure that the `JavaHome` key in `HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8.0_91` (replace with your version) has a directory path to a valid Java installation.
- If you're running a 64b Windows, ensure this for both the 64b and 32b versions of the registry (see https://support.microsoft.com/fr-dz/help/305097/how-to-view-the-system-registry-by-using-64-bit-versions-of-windows for how to view the 32b registry on a 64b machine).

Keep in mind, that Visual Studio is a 32b process and that, by default, it will run Antlr4 by looking for a 32b version of the JRE.  If, for some reason, you're building the solution outside of Visual Studio with 64b processes, the 64b version of the registry is used.

**Comment by sharwell** [comment]
@igitur Java is no longer required for generating code. The C# code generator is recommended instead. See the release notes for [v4.6.5-beta001](https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.6.5-beta001) for instructions on enabling it.
