### ISSUE TITLE
no rules accesibility (g3)

### ISSUE THREAD

**Issue by tdjastrzebski** [tunnelvisionlabs/antlr4cs#205]
Parser rules generated from Antlr3 grammar are all marked private.

**Comment by sharwell** [comment]
:memo: This is the repository for ANTLR 4, which does not support the feature you describe. The repository for the ANTLR 3 C# target is [antlr/antlrcs](https://github.com/antlr/antlrcs).

> Parser rules generated from Antlr3 grammar are all marked private.

This is by design. For any rule you want to call from outside code, mark it `public` or `protected` in your grammar file, [line this](https://github.com/antlr/antlrcs/blob/master/Antlr3/Grammars/ANTLR.g3#L238-L239).

**Comment by tdjastrzebski** [comment]
Thanks, I think years ago this feature was not available and all rules were generated public. I try to revitalize project created over to years ago
