### ISSUE TITLE
Runtime/Lexer::TokenNames is marked obsolete but not in the derived generated

### ISSUE THREAD

**Issue by DanMcLaughlin** [tunnelvisionlabs/antlr4cs#97]
Runtime/Lexer::TokenNames is marked Obsolete for some reason, but the overridden generated Lexer::TokenNames is not marked obsolete, this is an error in the Unity 3.5 Mono project. Why is it marked Obsolete at all?

**Comment by sharwell** [comment]
`TokenNames` is obsolete because the new `IVocabulary` interface provides well-defined behavior that covers a much wider variety of scenarios. The `TokenNames` property was not removed to reduce the difficulty of users to upgrade to the latest release.

I'll update the template to mark the property obsolete in generated code.

**Comment by sharwell** [comment]
@DanMcLaughlin I couldn't find any cases where `TokenNames` wasn't already marked `Obsolete`, but I took the opportunity to improve the messaging across the board.
